### ISSUE TITLE
[Feature Request] Status page.

### ISSUE THREAD

**Issue by gtuxyco** [PutterPlace/PokemonGo-Map-GUI-PHP#5]
I try to implement the status page but i can't figure out how to compare the password from the form with the server

**Comment by PutterPlace** [comment]
What password are you referring to? I'm not sure that I understand what you're asking.

**Comment by gtuxyco** [comment]
the map impement a status page for know the log of the workers in the web, and use a password that is defined in config.ini

**Comment by PutterPlace** [comment]
Gotcha. I based this off of a slightly offer cone of PokemonGo-Map, so I guess I'd have to look into it in the next couple of days. Any idea how it's pulling the logs of the workers? If the workers are logging their status to the database, then it'll be doable. Otherwise, I don't see it happening since, in this implementation, there is no direct communication between the workers and server. All data transferred between the two is strictly through MySQL.

**Comment by PutterPlace** [comment]
Slightly older clone of****

**Comment by PutterPlace** [comment]
I finally had a chance to rage a quick glance into this. Looks like later builds of PokemonGo-Map psh worker status to the db, so this is definitely doable in this implementation. Give me some time to implement it. :-)

**Comment by PutterPlace** [comment]
Forgot about this, but it's way past its prime now.
